version: "3.6"
services:
    present:
        image: node
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        working_dir: /app
        entrypoint: ["yarn"]
        command: ["start"]
    yarn:
        image: node
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["yarn"]
        command: ["--version"]
